# Generated by Django 6.0.3 on 2026-07-24 10:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('page_path', models.CharField(default='/', max_length=255)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collaborators/')),
                ('portfolio_link', models.CharField(blank=True, max_length=255, null=True)),
                ('github_link', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('role_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipe', models.CharField(blank=True, max_length=255)),
                ('tipe_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('ini_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('certificate', models.ImageField(blank=True, upload_to='certifications/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('position_en', models.CharField(blank=True, max_length=255, null=True)),
                ('work_place', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('ini_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTopics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topics_title', models.CharField(max_length=255)),
                ('topics_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('topics_en', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fontawesome_icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_icon', models.ImageField(null=True, upload_to='icons/')),
                ('project_title', models.CharField(max_length=255)),
                ('project_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField(null=True)),
                ('project_description_en', models.TextField(blank=True, null=True)),
                ('project_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True)),
                ('project_resorce_title', models.CharField(max_length=255)),
                ('project_resorce_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('project_resorce_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('project_resorce_list_en', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True)),
                ('project_resorce_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('project_resorce_tags_en', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True)),
                ('project_note', models.TextField(null=True)),
                ('project_note_en', models.TextField(blank=True, null=True)),
                ('project_github_rep_link', models.TextField(null=True)),
                ('add_on', models.DateTimeField(auto_now_add=True)),
                ('project_gallery', models.ManyToManyField(blank=True, to='MainApp.projectgallery')),
                ('project_topics', models.ManyToManyField(blank=True, to='MainApp.projecttopics')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('about_me', models.TextField(blank=True)),
                ('about_me_en', models.TextField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, upload_to='')),
                ('bio', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('topics', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField(blank=True)),
                ('location_en', models.TextField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, max_length=255)),
                ('expertise_en', models.CharField(blank=True, max_length=255, null=True)),
                ('github_user', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('date_birth', models.DateField(blank=True)),
                ('ini_date_exp', models.DateField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('linkedin_link', models.CharField(blank=True, max_length=255)),
                ('img_zoom', models.FloatField(blank=True, default=1.0, null=True)),
                ('img_x', models.FloatField(blank=True, default=0.0, null=True)),
                ('img_y', models.FloatField(blank=True, default=0.0, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='MainApp.tags')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
