# Generated by Django 6.0.3 on 2026-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
