# Generated by Django 6.0.3 on 2026-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_myprojects_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
