# Generated by Django 6.0.3 on 2026-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_myprojects_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
