# Generated by Django 6.0.3 on 2026-07-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_profileinfo_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
