# Generated by Django 6.0.3 on 2026-07-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_formation_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='resume_en',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
