# Generated by Django 6.0.3 on 2026-07-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_profileinfo_resume_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='github_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='github_forks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='github_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='github_repo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='github_size_kb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='github_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='github_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
